server:
  port: 8081
  http2:
    enabled: true
  ssl:
    enabled: false
spring:
  cloud:
    gateway:
      routes:
        - id: json-hello
          uri: http://my-service:80/
          predicates:
            - Path=/user/**
          # filters:
          #   - name: JsonToGrpc
          #     args:
          #       protoDescriptor: classpath:hello.pb
          #       protoFile: classpath:hello.proto
          #       service: HelloWorldService
          #       method: sayHello
